name: On Release

on:
  push:
    tags:
      - v*

jobs:

  build:
    if: github.repository == 'hexlet/runit'
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Action for Heroku
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: hexlet-editor
          heroku_email: feycot@gmail.com
